ServiceName: ImageAnalysis

ModuleSwitch:
# 模块开关，请注意该名称需要与core中对应模块的文件夹名相同
  "ocr": True
  "seal_rec": True

RunArgs:
  cpu_threads: 1

Log:
  linux_save_root: "/opt/logs"  # linux系统下，日志保存路径
  windows_save_root: "D:/logs"  # windows下，日志保存路径
  retention_time: "14 days"  # 日志保留时长
  level: "INFO"  # 请大写 候选列表为：[DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL]

Web:
  ip: "0.0.0.0"  # web服务绑定的ip地址
  port: 18220  # web服务绑定的端口号
  workers: 2  # web服务器的进程数，由于该项目为CPU密集型计算项目，进程数*线程数不宜超过机器CPU线程数
  threads: 4  # web服务器的线程数，由于该项目为CPU密集型计算项目，进程数*线程数不宜超过机器CPU线程数
  timeout: 120  # web服务超时时间

